# Generated by Django 4.2.3 on 2023-07-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_business_code_businessuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessuser", old_name="user", new_name="username",
        ),
    ]
