# Generated by Django 4.2.6 on 2023-10-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address_detail",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="address_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="address_relate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
