# Generated by Django 4.2.6 on 2023-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_profile_address_detail_profile_address_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
