# Generated by Django 4.2.3 on 2023-07-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_user_businessuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(model_name="businessuser", name="id",),
        migrations.RemoveField(model_name="businessuser", name="username",),
        migrations.AddField(
            model_name="businessuser",
            name="user_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
