# Generated by Django 4.2.3 on 2023-07-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_businessuser_options_remove_businessuser_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business",
            field=models.BooleanField(default=False),
        ),
    ]
