# Generated by Django 4.2.6 on 2023-10-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_profile_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="face_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="insta_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
