# Generated by Django 4.2.3 on 2023-07-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_delete_businessuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="town",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
