# Generated by Django 4.2.3 on 2023-07-18 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
