# Generated by Django 4.2.3 on 2023-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_remove_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
