# Generated by Django 4.2.3 on 2023-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fulladdress",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
