# Generated by Django 4.2.3 on 2023-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="user/"),
        ),
    ]
