# Generated by Django 4.2.3 on 2023-07-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="address",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
