# Generated by Django 4.2.3 on 2023-07-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
