# Generated by Django 4.2.3 on 2023-07-19 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="blog.post",
            ),
        ),
    ]
