# Generated by Django 4.2.3 on 2023-07-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="blog/"),
        ),
    ]
