# Generated by Django 4.2.3 on 2023-07-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_remove_post_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default=1, upload_to="blog/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
