# Generated by Django 4.2.3 on 2023-07-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_post_image_delete_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
    ]
