# Generated by Django 4.2.3 on 2023-07-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, default=1, upload_to="blog/"),
            preserve_default=False,
        ),
    ]
