# Generated by Django 4.2.3 on 2023-10-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_address_alter_post_name'),
        ('blog', '0021_post_like_users'),
    ]

    operations = [
    ]
