# Generated by Django 4.2.3 on 2023-10-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_merge_20231013_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_users',
        ),
    ]
