# Generated by Django 4.2.3 on 2023-10-17 01:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0023_remove_post_like_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="thumbnail",
        ),
    ]
