# Generated by Django 4.2.6 on 2023-10-24 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0024_remove_post_image_remove_post_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="writer",
        ),
    ]
