# Generated by Django 4.2.6 on 2023-11-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0026_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
